on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          #- target: x86_64-apple-darwin
          #  archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile
        env:
          RUSTTARGET: ${{ matrix.target }}
        run: |
          cargo install cross
          cd Hookstaller
          cross build --release --target $RUSTTARGET
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.events.inputs.release_version }}
          release_name: ${{ github.events.inputs.release_version }}
          prerelease: true
      - name: Push to release
        run: gh release upload ${{ github.events.inputs.release_version }} ./target/release/*

        
