on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true

jobs:
  release:
    name: Release {{ github.events.inputs.release_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        run: |
          cargo install cross
          cd Hookstaller
          cross build --release --target x86_64-pc-windows-gnu
          cross build --release --target x86_64-unknown-linux-musl
          gh release create ${{ github.events.inputs.release_version }} ./target/x86_64-pc-windows-gnu/release/*,./target/x86_64-unknown-linux-musl/release/* --prerelease
